"""atributo platfom from social media alterado para não ser obrigatório

Revision ID: 82a078e0f702
Revises: 7616125350c8
Create Date: 2025-02-09 15:33:11.877419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82a078e0f702'
down_revision: Union[str, None] = '7616125350c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_media', 'platform_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('social_media', 'platform_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
