"""alterado nomes dos atributos da entidade management_hotel do banco de dados

Revision ID: 8efdf485c377
Revises: f04d2460650b
Create Date: 2025-03-08 17:30:26.835881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8efdf485c377'
down_revision: Union[str, None] = 'f04d2460650b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('management_hotel', sa.Column('image_hotel_url', sa.String(), nullable=True))
    op.add_column('management_hotel', sa.Column('instagram_url', sa.String(), nullable=True))
    op.add_column('management_hotel', sa.Column('facebook_url', sa.String(), nullable=True))
    op.drop_column('management_hotel', 'image_url')
    op.drop_column('management_hotel', 'platform_name')
    op.drop_column('management_hotel', 'url_social_media')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('management_hotel', sa.Column('url_social_media', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('management_hotel', sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('management_hotel', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('management_hotel', 'facebook_url')
    op.drop_column('management_hotel', 'instagram_url')
    op.drop_column('management_hotel', 'image_hotel_url')
    # ### end Alembic commands ###
