"""Adicionado hotel_id a service

Revision ID: 96a30f4cb4d6
Revises: 8a596ee54e09
Create Date: 2025-01-26 17:06:05.261288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96a30f4cb4d6'
down_revision: Union[str, None] = '8a596ee54e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('hotel_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'hotels', ['hotel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'hotel_id')
    # ### end Alembic commands ###
