"""atributo reception_phone e reservation_phone adicionados a hotel rota patch

Revision ID: d4c2d540b243
Revises: 82a078e0f702
Create Date: 2025-02-09 17:20:59.810368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4c2d540b243'
down_revision: Union[str, None] = '82a078e0f702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('reception_phone', sa.String(), nullable=True))
    op.add_column('hotels', sa.Column('reservation_phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hotels', 'reservation_phone')
    op.drop_column('hotels', 'reception_phone')
    # ### end Alembic commands ###
