"""removido social_media e substituido por ManagementHotel agregando alguns atributos da entidade

Revision ID: dd139ab6e8ee
Revises: 22aeff4cfc05
Create Date: 2025-03-08 14:29:21.805529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd139ab6e8ee'
down_revision: Union[str, None] = '22aeff4cfc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_hotel ',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('url_social_media', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('wifi_network', sa.String(), nullable=True),
    sa.Column('wifi_password', sa.String(), nullable=True),
    sa.Column('reception_phone', sa.String(), nullable=True),
    sa.Column('reservation_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('social_media')
    op.add_column('departments', sa.Column('image_url', sa.String(), nullable=False))
    op.drop_column('hotels', 'reservation_phone')
    op.drop_column('hotels', 'wifi_network')
    op.drop_column('hotels', 'wifi_password')
    op.drop_column('hotels', 'reception_phone')
    op.add_column('services', sa.Column('image_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'image_url')
    op.add_column('hotels', sa.Column('reception_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('wifi_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('wifi_network', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('reservation_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('departments', 'image_url')
    op.create_table('social_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='social_media_hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='social_media_pkey')
    )
    op.drop_table('management_hotel ')
    # ### end Alembic commands ###
