"""retirado espaço do final de nome da tabela management_hotel

Revision ID: f04d2460650b
Revises: dd139ab6e8ee
Create Date: 2025-03-08 17:22:28.267158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f04d2460650b'
down_revision: Union[str, None] = 'dd139ab6e8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_hotel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('url_social_media', sa.String(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('wifi_network', sa.String(), nullable=True),
    sa.Column('wifi_password', sa.String(), nullable=True),
    sa.Column('reception_phone', sa.String(), nullable=True),
    sa.Column('reservation_phone', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('management_hotel ')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('management_hotel ',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url_social_media', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('wifi_network', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wifi_password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reception_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('reservation_phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name='management_hotel _hotel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='management_hotel _pkey')
    )
    op.drop_table('management_hotel')
    # ### end Alembic commands ###
