"""Inserido atributo imagem para entidade Amenity

Revision ID: 10c2f10f108c
Revises: 8efdf485c377
Create Date: 2025-03-16 12:49:46.474572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c2f10f108c'
down_revision: Union[str, None] = '8efdf485c377'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('amenities', sa.Column('image_amenity_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amenities', 'image_amenity_url')
    # ### end Alembic commands ###
