"""Add start_time and end_time like string

Revision ID: 22aeff4cfc05
Revises: e602a417f546
Create Date: 2025-02-23 18:12:46.626453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22aeff4cfc05'
down_revision: Union[str, None] = 'e602a417f546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('departments', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'end_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    op.alter_column('departments', 'start_time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
