"""separando atributos de rede sociais e amenities de hotel

Revision ID: 7616125350c8
Revises: 96a30f4cb4d6
Create Date: 2025-02-09 14:14:10.285371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7616125350c8'
down_revision: Union[str, None] = '96a30f4cb4d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('social_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('hotels', 'social_media')
    op.drop_column('hotels', 'amenity')
    op.drop_column('hotels', 'end_time')
    op.drop_column('hotels', 'start_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('start_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('end_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('amenity', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hotels', sa.Column('social_media', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('social_media')
    op.drop_table('amenities')
    # ### end Alembic commands ###
