"""Add start_time and end_time to departments

Revision ID: e602a417f546
Revises: d4c2d540b243
Create Date: 2025-02-10 20:25:20.145240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e602a417f546'
down_revision: Union[str, None] = 'd4c2d540b243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('departments', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('services', sa.Column('start_time', sa.Time(), nullable=True))
    op.add_column('services', sa.Column('end_time', sa.Time(), nullable=True))
    op.add_column('services', sa.Column('is_24_hours', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'is_24_hours')
    op.drop_column('services', 'end_time')
    op.drop_column('services', 'start_time')
    op.drop_column('departments', 'end_time')
    op.drop_column('departments', 'start_time')
    # ### end Alembic commands ###
